/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_EMC_B1_00 (coord F3), SEMC_D0/U13[2] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D0_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D0_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D0_CHANNEL                                        0U   /*!< Signal channel */

/* GPIO_EMC_B1_01 (coord F2), SEMC_D1/U13[4]/U14A[J4] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D1_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D1_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D1_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_EMC_B1_02 (coord G4), SEMC_D2/U13[5] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D2_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D2_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D2_CHANNEL                                        2U   /*!< Signal channel */

/* GPIO_EMC_B1_03 (coord E4), SEMC_D3/U13[7] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D3_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D3_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D3_CHANNEL                                        3U   /*!< Signal channel */

/* GPIO_EMC_B1_04 (coord H5), SEMC_D4/U13[8] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D4_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D4_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D4_CHANNEL                                        4U   /*!< Signal channel */

/* GPIO_EMC_B1_05 (coord F4), SEMC_D5/U13[10] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D5_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D5_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D5_CHANNEL                                        5U   /*!< Signal channel */

/* GPIO_EMC_B1_06 (coord H4), SEMC_D6/U13[11] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D6_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D6_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D6_CHANNEL                                        6U   /*!< Signal channel */

/* GPIO_EMC_B1_07 (coord H3), SEMC_D7/U13[13] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D7_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D7_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D7_CHANNEL                                        7U   /*!< Signal channel */

/* GPIO_EMC_B1_30 (coord E3), SEMC_D8/U13[42] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D8_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D8_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D8_CHANNEL                                        8U   /*!< Signal channel */

/* GPIO_EMC_B1_31 (coord D2), SEMC_D9/U13[44] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D9_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D9_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D9_CHANNEL                                        9U   /*!< Signal channel */

/* GPIO_EMC_B1_32 (coord D1), SEMC_D10/U13[45] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D10_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D10_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D10_CHANNEL                                      10U   /*!< Signal channel */

/* GPIO_EMC_B1_33 (coord E2), SEMC_D11/U13[47] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D11_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D11_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D11_CHANNEL                                      11U   /*!< Signal channel */

/* GPIO_EMC_B1_34 (coord E1), SEMC_D12/U13[48] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D12_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D12_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D12_CHANNEL                                      12U   /*!< Signal channel */

/* GPIO_EMC_B1_35 (coord F1), SEMC_D13/U13[50] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D13_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D13_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D13_CHANNEL                                      13U   /*!< Signal channel */

/* GPIO_EMC_B1_36 (coord G1), SEMC_D14/U13[51] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D14_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D14_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D14_CHANNEL                                      14U   /*!< Signal channel */

/* GPIO_EMC_B1_37 (coord H1), SEMC_D15/U13[53] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D15_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D15_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D15_CHANNEL                                      15U   /*!< Signal channel */

/* GPIO_EMC_B1_09 (coord A3), SEMC_A0/U13[23]/U25[23] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A0_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A0_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A0_CHANNEL                                        0U   /*!< Signal channel */

/* GPIO_EMC_B1_10 (coord A2), SEMC_A1/U13[24]/U25[24] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A1_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A1_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A1_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_EMC_B1_11 (coord C2), SEMC_A2/U13[25]/U25[25] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A2_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A2_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A2_CHANNEL                                        2U   /*!< Signal channel */

/* GPIO_EMC_B1_12 (coord C5), SEMC_A3/U13[26]/U25[26] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A3_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A3_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A3_CHANNEL                                        3U   /*!< Signal channel */

/* GPIO_EMC_B1_13 (coord D5), SEMC_A4/U13[29]/U25[29] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A4_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A4_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A4_CHANNEL                                        4U   /*!< Signal channel */

/* GPIO_EMC_B1_14 (coord B1), SEMC_A5/U13[30]/U25[30] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A5_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A5_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A5_CHANNEL                                        5U   /*!< Signal channel */

/* GPIO_EMC_B1_15 (coord C1), SEMC_A6/U13[31]/U25[31] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A6_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A6_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A6_CHANNEL                                        6U   /*!< Signal channel */

/* GPIO_EMC_B1_16 (coord D3), SEMC_A7/U13[32]/U25[32] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A7_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A7_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A7_CHANNEL                                        7U   /*!< Signal channel */

/* GPIO_EMC_B1_17 (coord B3), SEMC_A8/U13[33]/U25[33] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A8_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A8_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A8_CHANNEL                                        8U   /*!< Signal channel */

/* GPIO_EMC_B1_18 (coord B4), SEMC_A9/U13[34]/U25[34]/U14A[D5] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A9_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A9_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A9_CHANNEL                                        9U   /*!< Signal channel */

/* GPIO_EMC_B1_23 (coord B2), SEMC_A10/U13[22]/U25[22] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A10_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A10_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A10_CHANNEL                                      10U   /*!< Signal channel */

/* GPIO_EMC_B1_19 (coord C4), SEMC_A11/U13[35]/U25[35]/U14A[C7] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A11_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A11_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A11_CHANNEL                                      11U   /*!< Signal channel */

/* GPIO_EMC_B1_20 (coord C3), SEMC_A12/U13[36]/U25[36]/U14A[D4] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A12_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A12_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A12_CHANNEL                                      12U   /*!< Signal channel */

/* GPIO_EMC_B1_21 (coord G2), SEMC_BA0/U13[20]/U25[20] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_BA0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_BA0_SIGNAL                                        BA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_BA0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_B1_22 (coord H2), SEMC_BA1/U13[21]/U25[21]/U14A[C4] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_BA1_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_BA1_SIGNAL                                        BA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_BA1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_B1_26 (coord J3), SEMC_CLK/U13[38]/U25[38] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CLK_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CLK_SIGNAL                                  semc_clk   /*!< Signal name */

/* GPIO_EMC_B1_28 (coord E5), SEMC_WE/U13[16]/U25[16] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_WE_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_WE_SIGNAL                                    semc_we   /*!< Signal name */

/* GPIO_EMC_B1_24 (coord J5), SEMC_CAS/U13[17]/U25[17] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CAS_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CAS_SIGNAL                                  semc_cas   /*!< Signal name */

/* GPIO_EMC_B1_25 (coord J4), SEMC_RAS/U13[18]/U25[18] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_RAS_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_RAS_SIGNAL                                  semc_ras   /*!< Signal name */

/* GPIO_EMC_B1_08 (coord F5), SEMC_DM0/U13[15] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM0_SIGNAL                                        DM   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_B1_38 (coord J1), SEMC_DM1/U13[39] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM1_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM1_SIGNAL                                        DM   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_B2_00 (coord K2), SEMC_D16/U25[2] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D16_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D16_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D16_CHANNEL                                      16U   /*!< Signal channel */

/* GPIO_EMC_B2_01 (coord K4), SEMC_D17/U25[4] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D17_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D17_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D17_CHANNEL                                      17U   /*!< Signal channel */

/* GPIO_EMC_B2_02 (coord K3), SEMC_D18/U25[5] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D18_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D18_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D18_CHANNEL                                      18U   /*!< Signal channel */

/* GPIO_EMC_B2_03 (coord R1), SEMC_D19/U25[7] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D19_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D19_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D19_CHANNEL                                      19U   /*!< Signal channel */

/* GPIO_EMC_B2_04 (coord M1), SEMC_D20/U25[8] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D20_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D20_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D20_CHANNEL                                      20U   /*!< Signal channel */

/* GPIO_EMC_B2_05 (coord N1), SEMC_D21/U25[10] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D21_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D21_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D21_CHANNEL                                      21U   /*!< Signal channel */

/* GPIO_EMC_B2_06 (coord T1), SEMC_D22/U25[11] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D22_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D22_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D22_CHANNEL                                      22U   /*!< Signal channel */

/* GPIO_EMC_B2_07 (coord M3), SEMC_D23/U25[13] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D23_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D23_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D23_CHANNEL                                      23U   /*!< Signal channel */

/* GPIO_EMC_B2_09 (coord N2), SEMC_D24/U25[42] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D24_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D24_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D24_CHANNEL                                      24U   /*!< Signal channel */

/* GPIO_EMC_B2_10 (coord R2), SEMC_D25/U25[44] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D25_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D25_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D25_CHANNEL                                      25U   /*!< Signal channel */

/* GPIO_EMC_B2_11 (coord L4), SEMC_D26/U25[45] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D26_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D26_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D26_CHANNEL                                      26U   /*!< Signal channel */

/* GPIO_EMC_B2_12 (coord M2), SEMC_D27/U25[47] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D27_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D27_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D27_CHANNEL                                      27U   /*!< Signal channel */

/* GPIO_EMC_B2_13 (coord K5), SEMC_D28/U25[48] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D28_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D28_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D28_CHANNEL                                      28U   /*!< Signal channel */

/* GPIO_EMC_B2_14 (coord M4), SEMC_D29/U25[50] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D29_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D29_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D29_CHANNEL                                      29U   /*!< Signal channel */

/* GPIO_EMC_B2_15 (coord L2), SEMC_D30/U25[51] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D30_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D30_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D30_CHANNEL                                      30U   /*!< Signal channel */

/* GPIO_EMC_B2_16 (coord P2), SEMC_D31/U25[53] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D31_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D31_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D31_CHANNEL                                      31U   /*!< Signal channel */

/* GPIO_EMC_B2_08 (coord P1), SEMC_DM2/U25[15] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM2_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM2_SIGNAL                                        DM   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_B2_17 (coord T2), SEMC_DM3/U25[39] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM3_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM3_SIGNAL                                        DM   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM3_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_EMC_B1_27 (coord G5), SEMC_CKE/U13[37]/U25[37] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CKE_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CKE_SIGNAL                                  semc_cke   /*!< Signal name */

/* GPIO_EMC_B1_29 (coord E6), SEMC_CS0/U13[19]/U25[19] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CS0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CS0_SIGNAL                                        CS   /*!< Signal name */
#define BOARD_INITPINS_SEMC_CS0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_B1_39 (coord J2), SEMC_DQS */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DQS_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DQS_SIGNAL                                  semc_dqs   /*!< Signal name */

/* GPIO_EMC_B1_40 (coord K1), SEMC_RDY/U14A[C8] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_RDY_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_RDY_SIGNAL                                  semc_rdy   /*!< Signal name */

/* GPIO_EMC_B2_19 (coord U2), ENET_RGMII_MDC */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_MDC_PERIPHERAL                            SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_MDC_SIGNAL                                CLKX   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_MDC_CHANNEL                                 0U   /*!< Signal channel */

/* GPIO_EMC_B2_20 (coord R3), ENET_RGMII_MDIO */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_MDIO_PERIPHERAL                           SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_MDIO_SIGNAL                               CLKX   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_MDIO_CHANNEL                                1U   /*!< Signal channel */

/* GPIO_EMC_B1_41 (coord L1), SEMC_CSX0/U14A[C6] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CSX0_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CSX0_SIGNAL                                      CSX   /*!< Signal name */
#define BOARD_INITPINS_SEMC_CSX0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_EMC_B2_18 (coord N3), SEMC_DQS4 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DQS4_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DQS4_SIGNAL                                semc_dqs4   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
